const USER_LOGIN_REQUESTED = "USER_LOGIN_REQUESTED";
const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
const USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";

const USER_REGISTER_REQUESTED = "USER_REGISTER_REQUESTED";
const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
const USER_REGISTER_SUCCESSFUL = "USER_REGISTER_SUCCESSFUL";

export {
  USER_LOGIN_REQUESTED,
  USER_LOGIN_FAILED,
  USER_LOGIN_SUCCESSFUL,
  USER_REGISTER_REQUESTED,
  USER_REGISTER_FAILED,
  USER_REGISTER_SUCCESSFUL,
};
